services:
  php:
    image: php:8.0-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    env_file:
      - ./.env
    working_dir: /var/www/html

    command: php-fpm -F
    ##    command: tail -f /dev/null
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${DB_PORT}:5432"
